on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Lint

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.2.1
      env:
        SHELLCHECK_OPTS: -e SC1091,SC2164,SC2034,SC1072,SC1073,SC1009

  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shfmt
      uses: bltavares/actions/shfmt@master
      env:
        SHFMT_ARGS: -d

  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.2
